import { BlogPost } from './supabase';

export const DEMO_BLOG_POSTS: BlogPost[] = [
  {
    id: 'demo-1',
    title: 'Free Printable Multiplication Worksheets for Kids',
    content: '<p>Multiplication is one of the core math skills every child needs. Our free printable multiplication worksheets make learning fun and engaging.</p><p>These worksheets cover everything from basic times tables to more advanced multiplication problems, perfect for grades 2-5.</p><h2>What You Get</h2><ul><li>Times tables 1-12</li><li>Mixed multiplication problems</li><li>Word problems</li><li>Answer keys included</li></ul><p>Print as many copies as you need for home or classroom use!</p>',
    excerpt: 'Discover our collection of free printable multiplication worksheets designed to help kids master times tables from 1 to 12 with fun and engaging exercises.',
    author: 'Sarah Johnson',
    image_url: 'https://images.pexels.com/photos/4261252/pexels-photo-4261252.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured_image: 'https://images.pexels.com/photos/4261252/pexels-photo-4261252.jpeg?auto=compress&cs=tinysrgb&w=800',
    image_alt: 'Child doing math worksheets',
    seo_title: 'Free Printable Multiplication Worksheets for Kids',
    seo_description: 'Download free printable multiplication worksheets for grades 2-5.',
    seo_keywords: 'multiplication worksheets, free printable, kids math',
    slug: 'free-printable-multiplication-worksheets',
    status: 'published',
    published_at: '2026-01-15T10:00:00Z',
    views: 1240,
    category_id: null,
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
  },
  {
    id: 'demo-2',
    title: 'Alphabet Tracing Worksheets: A Complete Guide for Parents',
    content: '<p>Learning to write the alphabet is a major milestone for young children. Tracing worksheets are one of the most effective tools for building letter recognition and fine motor skills.</p><p>Our alphabet tracing worksheets are designed by education experts and tested in real classrooms.</p><h2>Benefits of Tracing Practice</h2><ul><li>Improves fine motor skills</li><li>Builds letter recognition</li><li>Prepares for writing</li><li>Builds confidence</li></ul>',
    excerpt: 'Help your child learn to write with our beautifully designed alphabet tracing worksheets. Perfect for preschool and kindergarten students.',
    author: 'Emily Carter',
    image_url: 'https://images.pexels.com/photos/8363022/pexels-photo-8363022.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured_image: 'https://images.pexels.com/photos/8363022/pexels-photo-8363022.jpeg?auto=compress&cs=tinysrgb&w=800',
    image_alt: 'Child practicing writing alphabet',
    seo_title: 'Alphabet Tracing Worksheets Guide for Parents',
    seo_description: 'A complete guide to using alphabet tracing worksheets for preschool and kindergarten.',
    seo_keywords: 'alphabet tracing, worksheets, preschool, writing practice',
    slug: 'alphabet-tracing-worksheets-guide',
    status: 'published',
    published_at: '2026-01-20T10:00:00Z',
    views: 890,
    category_id: null,
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'demo-3',
    title: '10 Best Math Activities for Elementary School Students',
    content: '<p>Making math fun is the key to building a lifelong love of numbers. Here are our top 10 math activities that kids actually enjoy!</p><p>From hands-on games to printable worksheets, these activities cover addition, subtraction, multiplication, and division in engaging ways.</p><h2>Top Activities</h2><ol><li>Math Bingo</li><li>Number Line Hopscotch</li><li>Multiplication War (card game)</li><li>Math Scavenger Hunt</li><li>Fraction Pizza</li></ol>',
    excerpt: 'Engage your elementary students with these 10 creative and fun math activities that make learning numbers an adventure.',
    author: 'Michael Torres',
    image_url: 'https://images.pexels.com/photos/3769981/pexels-photo-3769981.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured_image: 'https://images.pexels.com/photos/3769981/pexels-photo-3769981.jpeg?auto=compress&cs=tinysrgb&w=800',
    image_alt: 'Students doing math activities',
    seo_title: '10 Best Math Activities for Elementary Students',
    seo_description: 'Discover 10 fun and engaging math activities for elementary school students.',
    seo_keywords: 'math activities, elementary school, fun math, kids',
    slug: '10-best-math-activities-elementary',
    status: 'published',
    published_at: '2026-02-01T10:00:00Z',
    views: 2100,
    category_id: null,
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-01T10:00:00Z',
  },
  {
    id: 'demo-4',
    title: 'Name Tracing Worksheets: Personalized Learning for Kids',
    content: '<p>Every child loves seeing their own name! Our personalized name tracing worksheets make learning to write personal and exciting.</p><p>Research shows that children learn letter formation faster when they practice with their own name. Our generator creates custom worksheets instantly.</p><h2>How to Use</h2><p>Simply type your child\'s name in our free generator and download a custom worksheet with dotted tracing lines, color guides, and fun illustrations.</p>',
    excerpt: 'Create personalized name tracing worksheets for your child in seconds. A fun way to learn letter formation using their own name.',
    author: 'Sarah Johnson',
    image_url: 'https://images.pexels.com/photos/1148998/pexels-photo-1148998.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured_image: 'https://images.pexels.com/photos/1148998/pexels-photo-1148998.jpeg?auto=compress&cs=tinysrgb&w=800',
    image_alt: 'Child writing their name',
    seo_title: 'Personalized Name Tracing Worksheets for Kids',
    seo_description: 'Create free personalized name tracing worksheets for your child instantly.',
    seo_keywords: 'name tracing, personalized worksheets, kids writing',
    slug: 'name-tracing-worksheets-personalized',
    status: 'published',
    published_at: '2026-02-10T10:00:00Z',
    views: 756,
    category_id: null,
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'demo-5',
    title: 'Division Worksheets: From Basic to Advanced',
    content: '<p>Division is often the trickiest of the four basic operations for students. Our division worksheets break it down step by step.</p><p>Whether your child is just starting with basic division or is ready for long division with remainders, we have worksheets for every level.</p><h2>Worksheet Levels</h2><ul><li>Basic division facts (1-10)</li><li>Division with remainders</li><li>Long division</li><li>Division word problems</li></ul>',
    excerpt: 'Master division with our comprehensive collection of division worksheets for all skill levels, from basic facts to long division.',
    author: 'Emily Carter',
    image_url: 'https://images.pexels.com/photos/6256073/pexels-photo-6256073.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured_image: 'https://images.pexels.com/photos/6256073/pexels-photo-6256073.jpeg?auto=compress&cs=tinysrgb&w=800',
    image_alt: 'Math division problems on paper',
    seo_title: 'Division Worksheets: Basic to Advanced',
    seo_description: 'Free printable division worksheets for all skill levels.',
    seo_keywords: 'division worksheets, long division, math worksheets',
    slug: 'division-worksheets-basic-to-advanced',
    status: 'published',
    published_at: '2026-02-20T10:00:00Z',
    views: 520,
    category_id: null,
    created_at: '2026-02-20T10:00:00Z',
    updated_at: '2026-02-20T10:00:00Z',
  },
  {
    id: 'demo-6',
    title: 'How to Make Homework Time More Fun for Your Child',
    content: '<p>Homework battles are real — but they don\'t have to be. With the right strategies, you can turn homework time into a positive experience.</p><p>We spoke with teachers and child psychologists to bring you the most effective tips for stress-free homework sessions.</p><h2>Top Tips</h2><ul><li>Create a dedicated homework space</li><li>Use a timer (Pomodoro technique for kids)</li><li>Offer choice in order of subjects</li><li>Use worksheets that make it visual</li><li>Celebrate small wins</li></ul>',
    excerpt: 'Transform homework battles into productive sessions with these expert-approved tips that make learning at home enjoyable for the whole family.',
    author: 'Michael Torres',
    image_url: 'https://images.pexels.com/photos/4145153/pexels-photo-4145153.jpeg?auto=compress&cs=tinysrgb&w=800',
    featured_image: 'https://images.pexels.com/photos/4145153/pexels-photo-4145153.jpeg?auto=compress&cs=tinysrgb&w=800',
    image_alt: 'Parent helping child with homework',
    seo_title: 'How to Make Homework Time Fun for Kids',
    seo_description: 'Expert tips to make homework time more enjoyable and productive for children.',
    seo_keywords: 'homework tips, kids study, parenting tips',
    slug: 'how-to-make-homework-fun',
    status: 'published',
    published_at: '2026-03-01T10:00:00Z',
    views: 1830,
    category_id: null,
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-03-01T10:00:00Z',
  },
];
